config/routes.rb
Rails.application.routes.draw do

  get 'quiz/start'
  post 'quiz/start'

  get 'quiz/next'
  post 'quiz/next'

  get 'quiz/back'
  post 'quiz/back'

  

  get 'synonyms/start'
  post 'synonyms/start'
  get 'synonyms/random'
  post 'synonyms/random'
  post 'synonyms/showanswer'
  get 'synonyms/showanswer'

  root to:'pages#welcome'
  get '/signup', to:'users#new'
  resources :users , only: [:new, :create]
  resources :sessions , only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_secure_token :confirmation_token
    validates :user_name, uniqueness: {case_sensitive: false}
    validates :mail , uniqueness: {case_sensitive: false}

    
    def to_session
        {id: id}
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    before_action :only_signed_in

    add_flash_types :success, :danger

    private

    def only_signed_in
        if !session[:auth ]|| !session[:auth]['id']
            redirect_to new_user_path, danger:"You don't have the right to access to this page please Log in"
        end 
    end
    

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  skip_before_action :only_signed_in, only: [:welcome]


  def welcome
  end
  
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
 


  $a = ""
  $k =0
 

  def start
    @base = params[:base]
    puts @base
    if (@base == "General")||(@base == nil)
      $qst = []
      $ans = []
      $n = 0
      m = File.open("/home/ali/Desktop/2ndyear/Anglais/playandlearn/app/quiz.txt", "r")
      m.each_line do |line|
        $n = $n +1
        if(line[0]=="Q")
          a = line.split('.')[1].strip
          $qst << a
        
        elsif (line[0]=="A")
          a = line.split('.')[1].strip
          $ans << a
        end
      end
      m.close


    elsif (@base == "Capitals")
      $qst = []
      $ans = []
      $n = 0
      m = File.open("/home/ali/Desktop/2ndyear/Anglais/playandlearn/app/capitals.txt", "r")
      m.each_line do |line|
        $n = $n +1
          $qst << line.split('—')[0].strip
          $ans << line.split('—')[1].strip
      end
      m.close
      
 
    end

    $frontt = $qst[$k]
    $backk = $ans[$k]

  end




    def next
      if $k<$qst.length
        $k=$k+1
        $frontt = $qst[$k]
        $backk = $ans[$k]
      end 

      redirect_to quiz_start_path
    end

    def back
      if $k>0
        $k=$k-1
        $frontt = $qst[$k]
        $backk = $ans[$k]
      end 
      redirect_to quiz_start_path 
    end
    


  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_action :only_signed_in, only: [:new, :create]

  
  def new
  end

  def create
    user_params = params.require(:users)
    @user = User.where(user_name: user_params[:username]).or(User.where(mail: user_params[:username])).first
    if @user and @user.authenticate(user_params[:password])
      session[:auth] = @user.to_session
      
      redirect_to root_path, success: "You're logged in" 
    else
      redirect_to new_session_path, danger: 'Password or Username incorrect please try agains'
    end

  end

  def destroy
  end
end

app/controllers/synonyms_controller.rb
class SynonymsController < ApplicationController

 # skip_before_action :only_signed_in, only: [:start]

  $dictio = Hash.new
  $words = []
  $linee = ""
  $a = ""
  def start
    f = File.open("/home/ali/Desktop/2ndyear/Anglais/playandlearn/app/controllers/synonyms_en.txt", "r")
    f.each_line do |line|
      a = line.split(', ')[0].strip
      $words << a
      $dictio[a] = line.split(',')[1].strip
    end
    f.close
   if (@Answer==$back)||(@Answer=="")
    $n = rand($words.length)
   end
    $front = $words[$n]
    $back = $dictio[$words[$n]] 
    @Answer = params[:Answer]
  end

  
  def random

    $n = rand($words.length)
    $show=false
    redirect_to synonyms_start_path

  end


  def showanswer
      $show = true
      redirect_to synonyms_start_path

  end








end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :only_signed_in, only: [:new, :create, :confirm]

    def new
        @user = User.new
    end

    def create
        user_params = params.require(:user).permit(:firstname, :last_name,:user_name,:level_english, :mail, :password)
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            UserMailer.confirm(@user).deliver_now
            redirect_to new_user_path, success: 'Your account is created successfully, please check your mails ;)'
            
        else
            redirect_to  new_user_path
        end

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/synonyms_helper.rb
module SynonymsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playandlearn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" style="padding-top: 0px;" href="/">LearnToPlay</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item active">
        <a class="nav-link"  href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      
      <li class="nav-item">
            <a class="nav-link"  style=" padding-left : 15px;" href="<%= "/synonyms/start"%>">Synonyms</a>
      </li>
          <li class="nav-item">
            <a class="nav-link"  style=" padding-left : 15px;" href="<%= "/quiz/start"%>">General Quiz</a>
      </li>
      <li class="nav-item">
        <a class="nav-link"  style=" padding-left : 630px;" href="/signup">Sign Up</a>
      </li>

       <li class="nav-item">
        <a class="nav-link"  style=" padding-left : 60px;" href="<%= new_session_path%>">Log In</a>
       </li>
    
    </ul>
    <form class="form-inline my-2 my-lg-0" style="position: absolute; top: 8px; right: 16px;  font-size: 18px;}">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
  
</nav>

<div class ="container">
  <% if flash[:success]%>
    <div class = "alert alert-success">
      <%flash[:success]%>
      <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
<% end %> 
    </div>
  <%end%>  

   <% if flash[:danger]%>
    <div class = "alert alert-danger">
      <%flash[:danger]%>
      <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
<% end %> 
    </div>
  <%end%>
</div>
    <%= yield %>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>

</html>

app/views/pages/login.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Signin Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sign-in/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <form class="form-signin">
  <img class="mb-4" src="http://playtolearnonline.com/templates/theme469/images/logo.gif" alt="" width="" height="">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  <label for="inputEmail" class="sr-only">Email address</label>
  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
</form>
</body>

app/views/pages/welcome.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>One Page Wonder - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/one-page-wonder.min.css" rel="stylesheet">


  

  <style>
.parallax {
  /* The image used */
  background-image: url("https://i.ibb.co/mJxbHXR/index.jpg");
  

  /* Set a specific height */
  min-height: 1000px; 

  /* Create the parallax scrolling effect */
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

@import url(https://fonts.googleapis.com/css?family=EB+Garamond|Cardo:400italic);


body {
    margin: 0;
    background-color: #6ee9cf;

}


.sandbox-correct-pronounciation {
  padding: 0em 0 2em 0;
}

.heading-correct-pronounciation {

  margin: auto;
  text-align: center;
  position: relative;
}


h1 {
  color: #fff;
  font-family: 'Cardo', serif;
  font-size: 1.5em;
  font-weight: normal;
  font-style: italic;
  letter-spacing: 0.1em;
  line-height: 2.2em;
}

em {
  font-family: 'EB Garamond', serif;
  font-size: 3.5em;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  display: block;
  font-style:normal;
  padding-top: 0.1em;
  text-shadow: 0.07em 0.07em 0 rgba(0, 0, 0, 0.1);
  
  &::before, &::after {
  content: "§";
  display: inline-block;
  -webkit-transform: rotate(90deg);
  -moz-transform: rotate(90deg);
  -o-transform: rotate(90deg);
  -ms-transform: rotate(90deg);
  transform: rotate(90deg);
    opacity: 0.2;
  margin: 0 0.6em;
  font-size: 0.5em;
}

}


.bottom {
  font-size: 1.5em;
  letter-spacing: 0.07em;
  font-size: 1em;
  display: block;
}
</style>

</head>


<body>
    
    
 <div class="sandbox sandbox-correct-pronounciation">
  <h1 class="heading heading-correct-pronounciation">
    Welcome to
    <em>PLAY TO LEARN</em>
"Beacause it's all about enjoying the journey and trying to get better every day."
  </h1>
</div>  


<div class="parallax"></div>
  <section>
    <div class="container" >
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5"  >
          <a href ="/synonyms/start">
            <img class="img-fluid rounded-circle" src="https://www.synonyms.com/root/app_common/img/top_logo_syn.png" alt="" >
          </a>
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Learning Synonyms</h2>
            <p>A synonym is a word or expression that has nearly the same meaning as another word or expression. Synonyms tend to be adjectives, adverbs and verbs, with relatively few nouns qualifying as true synonyms.
            Genarally beginners should  like learning synonyms thanks to online synonym games as well as online dictionaries, and that's what we're using here.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="p-5">
            <a href ="/quiz/start">
            <img class="img-fluid rounded-circle" src="https://cdn0.iconfinder.com/data/icons/online-education-butterscotch-vol-2/512/Questions_And_Answers-512.png" alt="">
            </a>

          </div>
        </div>
        <div class="col-lg-6">
          <div class="p-5">
            <h2 class="display-4">General knowledge quiz</h2>
            <p>This game  is a general knowledge quiz about diffirent topics. 
            Our quizzes are the perfect way to relax over a morning coffee or wind down before bed and also learn new things every day.</p>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyrights ? &copy; don't care bruh!!</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>



</body>

</html>

app/views/quiz/start.html.erb
<img class="mb-4" src="https://lingrolearning.com/wp-content/uploads/2018/03/Playing-to-learn_thumb46.jpg" style="padding-left: 380px;"  width="70%" height = "70%"">

<style>

 /* The flip card container - set the width and height to whatever you want. We have added the border property to demonstrate that the flip itself goes out of the box on hover (remove perspective if you don't want the 3D effect */
.flip-card {
  margin: 0 auto;
  background-color: transparent;
  width: 800px;
  height: 400px;
  border: medium dashed grey;
  perspective: 1000px; /* Remove this if you don't want the 3D effect */
}

/* This container is needed to position the front and back side */
.flip-card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: inherit;
  transition: transform 0.8s;
  transform-style: preserve-3d;
}

/* Do an horizontal flip when you move the mouse over the flip box container */
.flip-card:hover .flip-card-inner {
  transform: rotateY(180deg);
}

/* Position the front and back side */
.flip-card-front, .flip-card-back {
  position: absolute;
  width: 100%;
  height: 100%;
  backface-visibility: hidden;
}

/* Style the front side (fallback if image is missing) */
.flip-card-front {
  background-color: #69d764;
  color: black;
}

/* Style the back side */
.flip-card-back {
  background-color: dodgerblue;
  color: white;
  transform: rotateY(180deg);
} 
  span {

    width: 100%;
    padding: 0.25rem 0;
    font-size: 4rem;
    font-weight: Small-Caps;
  }

  .mycontainer {
    position: absolute;
        top: 50%;
        left: 50%;
        margin-right: -50%;
        transform: translate(-50%, -50%) 

  }



</style>

<script>

</script>




<div class= "panel panel-default">
  <div class="panel-heading"><p style = "font-family:georgia,garamond,serif;font-size:30px;font-style:italic;">
         The answer is on the back ;) </p></div>

         <%= form_tag do%>

<div class="form-group">
    <div class="col-md-6">
      <%=select_tag  :base ,"<option></option><option>General</option><option>Capitals</option>".html_safe, class:'form-control' , placeholder: "Please type your answer here" %>
    </div>
    <%=submit_tag "Go", class: "btn btn-primary"%>

</div>
<%end%>
            <div class="panel-body">
 <div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <div class= "mycontainer">
        <span><%=$frontt
        %></span>
            </div>

    </div>
    <div class="flip-card-back">
          <div class= "mycontainer">
        <span> <%= $backk%></span>
                  </div>
    </div>
  </div>
    </div>
  </div>

</div> 
</div>

<div class="form-group">

       <div class="col-md-6">

    <%= button_to 'Back', quiz_back_path, method: :post, class: "btn btn-primary"%>
        </div>
    <div class="col-md-6">

    <%= button_to 'Next', quiz_next_path, method: :post, class: "btn btn-primary"%>
        </div>

   


</div>
</div>

app/views/synonyms/start.html.erb
<img class="mb-4" src="https://lingrolearning.com/wp-content/uploads/2018/03/Playing-to-learn_thumb46.jpg" style="padding-left: 380px;"  width="70%" height = "70%"">

<style>

 /* The flip card container - set the width and height to whatever you want. We have added the border property to demonstrate that the flip itself goes out of the box on hover (remove perspective if you don't want the 3D effect */
.flip-card {
  margin: 0 auto;
  background-color: transparent;
  width: 800px;
  height: 400px;
  border: medium dashed grey;
  perspective: 1000px; /* Remove this if you don't want the 3D effect */
}

/* This container is needed to position the front and back side */
.flip-card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: inherit;
  transition: transform 0.8s;
  transform-style: preserve-3d;
}

/* Do an horizontal flip when you move the mouse over the flip box container */
.flip-card:hover .flip-card-inner {
  transform: rotateY(180deg);
}

/* Position the front and back side */
.flip-card-front, .flip-card-back {
  position: absolute;
  width: 100%;
  height: 100%;
  backface-visibility: hidden;
}

/* Style the front side (fallback if image is missing) */
.flip-card-front {
  background-color: #69d764;
  color: black;
}

/* Style the back side */
.flip-card-back {
  background-color: dodgerblue;
  color: white;
  transform: rotateY(180deg);
} 
  span {

    width: 100%;
    padding: 0.25rem 0;
    font-size: 8rem;
    font-weight: Small-Caps;
  }

  .mycontainer {
    position: absolute;
        top: 50%;
        left: 50%;
        margin-right: -50%;
        transform: translate(-50%, -50%) 

  }



</style>

<script>

</script>


<div class= "panel panel-default">
  <div class="panel-heading"><p style = "font-family:georgia,garamond,serif;font-size:30px;font-style:italic;">
         Turn the card for help ;) </p></div>
            <div class="panel-body">
 <div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <div class= "mycontainer">
        <span><%=$front
        %></span>
            </div>

    </div>
    <div class="flip-card-back">
          <div class= "mycontainer">
          <%k = ($back.length) -1%>
        <span> <%= $back[0] + "_ "*k%></span>
                  </div>
    </div>
  </div>
    </div>
  </div>

</div> 
</div>


<div class= "panel panel-default">
  <div class="panel-heading"><p style = "font-family:georgia,garamond,serif;font-size:30px;font-style:italic;">
         Your answer please ?</p></div>
            <div class="panel-body">
<%= form_tag do%>

<div class="form-group">
    <div class="col-md-6">
      <%=text_field_tag  :Answer ,nil, class:'form-control' , placeholder: "Please type your answer here" %>
    </div>
    <%=submit_tag "Submit my answser", class: "btn btn-primary"%>


</div>
<%end%>
<div class="form-group">
    <div class="col-md-6">

    <%= button_to 'Change word', synonyms_random_path, method: :post, class: "btn btn-primary"%>
        </div>
    <div class="col-md-6">

    <%= button_to 'Show answer', synonyms_showanswer_path, method: :post, class: "btn btn-primary"%>
    </div>

</div>
</div>

<% if @Answer==$back%>
    <%$n = rand($words.length)%>
    <img class="mb-4" src="https://memegenerator.net/img/instances/59866762/that-answer-is-correct.jpg",class="w3-border w3-padding">
    <%$show = false%>
 <%elsif @Answer != nil && @Answer != ""%>
    <img class="mb-4" src="https://meme.xyz/uploads/posts/t/l-21807-wrong.jpg",class="w3-border w3-padding",style="margin-left: auto;
    margin-right: auto">
        <%$show = false%>

    <h1>The answer was  : <%=$back%><h1>
    <%$n = rand($words.length)%>

<%end%>



<%if $show%>
    <h1>The answer is  : <%=$back%><h1>
<%end%>
</div>
</div>

app/views/users/new.html.erb
<img class="mb-4" src="https://lingrolearning.com/wp-content/uploads/2018/03/Playing-to-learn_thumb46.jpg" style="padding-left: 380px;"  width="70%" height = "70%"">

<div class = "container" style="padding-top: 50px; padding-left: 80px;">
    <% if @user.errors.any?%>
        <div class="alert alert-danger">
            <ul>
                <% @user.errors.full_messages.each do |message|%>
                    <li><%=message%></li>
                <%end%>
            </ul>
        </div>
    <%end%>


    <div  class="panel panel-default" >
        <div class="panel-heading"><p style = "font-family:georgia,garamond,serif;font-size:30px;font-style:italic;">
         SIGN UP</p></div>
            <div class="panel-body">
                <%= form_for @user, html: {class:'form-horizontal'} do |f|%>
                    
                    <div class="form-group">
                        <%= f.label :firstname, "First Name", class: 'col-md-4 control-label' %>
                        <div class="col-md-6">
                            <%=f.text_field :firstname,  class:'form-control'%>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= f.label :last_name, "Last Name", class: 'col-md-4 control-label' %>
                        <div class="col-md-6">
                            <%=f.text_field :last_name,  class:'form-control'%>
                        </div>
                    </div>


                    <div class="form-group">
                        <%= f.label :level_english, "Your English level", class: 'col-md-4 control-label' %>
                        <div class="col-md-6">
                            <%=f.select :level_english, options_for_select(["Beginner", "Intermediate", "Advanced ", "Proficient ", "Fluent"]), class:'form-control'%>         
                        </div>
                    </div>


                    <div class="form-group">
                        <%= f.label :user_name, "User Name", class: 'col-md-4 control-label' %>
                        <div class="col-md-6">
                            <%=f.text_field :user_name,  class:'form-control'%>
                        </div>
                    </div>

                    <div class="form-group">
                        <%= f.label :mail, "E-mail", class: 'col-md-4 control-label' %>
                        <div class="col-md-6">
                            <%=f.email_field :mail,  class:'form-control'%>
                        </div>

                    </div>

                    <div class="form-group">
                        <%= f.label :password, "Password", class: 'col-md-4 control-label' %>
                        <div class="col-md-6">
                            <%=f.password_field :password,  class:'form-control'%>
                        </div>
                                            </div>


                      <div class="form-group">
                        <%= f.label :password_confirmation, "Password Confirmation", class: 'col-md-4 control-label' %>
                        <div class="col-md-6">
                            <%=f.password_field :password_confirmation,  class:'form-control'%>
                           
                        </div>

                        <div class="form-group" style="padding-top: 50px;">
                            <div class="col-md-offset-4 col-md-6">
                                <button type="Submit" class="btn btn-primary">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </div>

                <%end%>
            </div>
        </div>
    </div>
</div>